pool:
  vmImage: vs2017-win2016

steps:
- task: NodeTool@0
  inputs:
    versionSpec: 8.x
  displayName: Install Node 8

- script: |
    set SKIP_DOWNLOAD=true
    npm install
  displayName: npm install  

- script: npm run lint
  displayName: npm run lint

- script: |
    npm test
    npm run test:browsers
  displayName: Test with Node 8

- task: NodeTool@0
  inputs:
    versionSpec: 10.x
  displayName: Install Node 10

- script: |
    npm test
    npm run test:browsers
  displayName: Test with Node 10

- task: NodeTool@0
  inputs:
    versionSpec: 11.x
  displayName: Install Node 11

- script: |
    npm test
    npm run test:browsers
  displayName: Test with Node 11

- script: .\node_modules\.bin\node-pre-gyp package
  displayName: node-pre-gyp package

- script: if not "%BUILD_SOURCEVERSIONMESSAGE% == "%BUILD_SOURCEVERSIONMESSAGE:[publish binary]=%" call node_modules\.bin\node-pre-gyp --msvs_version=2017 publish
  displayName: node-pre-gyp publish (optional)
